version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin-tslint"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: ioredis
    versions:
    - 4.24.3
    - 4.24.5
    - 4.25.0
    - 4.26.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.35
    - 14.14.37
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.10
    - 7.13.12
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: chai
    versions:
    - 4.3.3
    - 4.3.4
  - dependency-name: socket.io
    versions:
    - 2.4.0
    - 3.1.2
    - 4.0.0
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.2
    - 4.0.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: nock
    versions:
    - 13.0.11
  - dependency-name: nodemon
    versions:
    - 2.0.7
  - dependency-name: express-rate-limit
    versions:
    - 5.2.6
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.10.1
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: tslint
    versions:
    - 6.1.3
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: ts-loader
    versions:
    - 8.0.10
  - dependency-name: applicationinsights
    versions:
    - 1.8.10
  - dependency-name: "@types/chai-as-promised"
    versions:
    - 7.1.3
  - dependency-name: ioredis-mock
    versions:
    - 5.2.4
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: "@types/socket.io"
    versions:
    - 2.1.12
  - dependency-name: "@hmcts/nodejs-healthcheck"
    versions:
    - 1.7.0
