version: '2'

services:
  em-icp-api:
    image: hmctspublic.azurecr.io/em/icp:aat-a808eaa1
    environment:
      - IDAM_API_BASE_URI=http://idam-api:5000
      - OPEN_ID_API_BASE_URI=https://idam-api.aat.platform.hmcts.net/o
      - OIDC_ISSUER_BASE_URI=https://forgerock-am.service.core-compute-idam-aat.internal:8443/openam/oauth2/hmcts
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
