redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS
appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY

idam:
  url: IDAM_API_BASE_URL

s2s:
  url: IDAM_S2S_URL
  secret: S2S_KEY

rateLimit:
  time: RATE_LIMIT_TIME
  max: RATE_LIMITE_MAX
pact:
  branchName: "PACT_BRANCH_NAME"
  brokerUrl: "PACT_BROKER_URL"
  consumerVersion: "PACT_CONSUMER_VERSION"
