apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Digital Court Presentation Application
name: em-icp
home: https://github.com/hmcts/em-icp-api
version: 0.2.1
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: '@hmctspublic'
  - name: redis
    version: 10.6.18
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - pr
